/**
 * Stays finance API — the Stays mirror of `features/finance/api.js`: the same
 * function names and shapes the finance page consumes, backed by the stays
 * mock today and the `/stays/supplier/finance/...` endpoints when the backend
 * ships. Amounts are USD, like the Experiences finance page.
 */
import api from "@/lib/axios";
import { formatCurrency } from "@/lib/utils";
import { staysMock } from "./mock/store";
import { staysUsesMockData } from "./api";

const BASE = "/stays/supplier";
const requestConfig = { skipGlobalErrorHandler: true };

export async function fetchFinanceSummary() {
  if (staysUsesMockData) return staysMock.getFinanceSummary();
  const response = await api.get(`${BASE}/finance/summary`, requestConfig);
  return response.data?.data || {};
}

export async function fetchFinanceEarnings(params = {}) {
  if (staysUsesMockData) return staysMock.getFinanceEarnings(params);
  const response = await api.get(`${BASE}/finance/earnings`, { ...requestConfig, params });
  const payload = response.data?.data || {};
  return {
    earnings: (payload.earnings || []).map((item) => ({
      id: item.id,
      bookingId: item.bookingId,
      bookingNumber: item.bookingNumber,
      travelDate: item.travelDate,
      stayDate: item.travelDate,
      paidAt: item.paidAt,
      grossAmount: Number(item.grossAmount) || 0,
      supplierPayout: Number(item.supplierPayout) || 0,
      commissionAmount: Number(item.platformCommission) || 0,
      commissionRate: Number(item.commissionRate) || 0,
      currency: item.currency || "USD",
      payoutStatus: item.payoutStatus,
      status: item.status,
      property: item.property?.name || "—",
      room: item.room || "—",
      customer: item.customer?.name || "—",
      payoutRequest: item.payoutRequest || null,
      openDispute: item.openDispute || null,
    })),
    summary: payload.summary || {},
    pagination: payload.pagination || null,
  };
}

export async function fetchPayoutRequests(params = {}) {
  if (staysUsesMockData) return staysMock.getPayoutRequests(params);
  const response = await api.get(`${BASE}/finance/payouts/requests`, { ...requestConfig, params });
  const payload = response.data?.data || {};
  return {
    requests: (payload.requests || []).map((request) => ({
      id: request.id,
      requestNumber: request.requestNumber,
      amount: Number(request.amount) || 0,
      currency: request.currency || "USD",
      bookingCount: request.bookingCount || 0,
      status: request.status,
      cycleLabel: request.cycleLabel,
      reference: request.reference || "",
      createdAt: request.createdAt,
      completedAt: request.completedAt,
      rejectedReason: request.rejectedReason || "",
      autoGenerated: Boolean(request.autoGenerated),
      method: request.payoutMethod
        ? request.payoutMethod.type?.replace(/_/g, " ") || "—"
        : "—",
    })),
    pagination: payload.pagination || null,
  };
}

export async function createPayoutRequest(payload = {}) {
  if (staysUsesMockData) return staysMock.createPayoutRequest(payload);
  const response = await api.post(`${BASE}/finance/payout/request`, payload, requestConfig);
  return response.data?.data;
}

export async function cancelPayoutRequest(id) {
  if (staysUsesMockData) return staysMock.cancelPayoutRequest(id);
  const response = await api.patch(`${BASE}/finance/payouts/requests/${id}/cancel`, {}, requestConfig);
  return response.data?.data;
}

export async function fetchPayoutSettings() {
  if (staysUsesMockData) return staysMock.getPayoutSettings();
  const response = await api.get(`${BASE}/finance/payout-settings`, requestConfig);
  return response.data?.data || {};
}

export async function updatePayoutSettings(cycle) {
  if (staysUsesMockData) return staysMock.updatePayoutSettings(cycle);
  const response = await api.patch(`${BASE}/finance/payout-settings`, { cycle }, requestConfig);
  return response.data?.data || {};
}

export async function getFinanceCharges() {
  if (staysUsesMockData) return staysMock.getFinanceCharges();
  const response = await api.get(`${BASE}/finance/charges`, requestConfig);
  const payload = response.data?.data || {};
  const charges = (payload.charges || []).map((charge) => ({
    id: charge.id,
    amount: Number(charge.amount) || 0,
    currency: charge.currency || "USD",
    reason: charge.reason || "",
    status: charge.status,
    notes: charge.notes || "",
    createdAt: charge.createdAt,
    settledAt: charge.settledAt,
    bookingId: charge.bookingId,
    bookingNumber: charge.bookingNumber || "—",
    payoutRequestId: charge.payoutRequestId,
    payoutRequestNumber: charge.payoutRequestNumber || null,
  }));
  const openTotals = Object.entries(payload.openTotals || {}).map(([currency, amount]) => ({
    currency,
    amount: Number(amount) || 0,
  }));
  return { charges, openTotals };
}

export async function fetchFinanceDisputes(params = {}) {
  if (staysUsesMockData) return staysMock.getFinanceDisputes(params);
  const response = await api.get(`${BASE}/finance/disputes`, { ...requestConfig, params });
  const payload = response.data?.data || {};
  return {
    disputes: (payload.disputes || []).map((dispute) => ({
      id: dispute.id,
      disputeNumber: dispute.disputeNumber,
      reason: dispute.reason,
      description: dispute.description || "",
      status: dispute.status,
      resolution: dispute.resolution || "",
      refundAmount: dispute.refundAmount == null ? null : Number(dispute.refundAmount),
      createdAt: dispute.createdAt,
      resolvedAt: dispute.resolvedAt,
      bookingNumber: dispute.booking?.bookingNumber || "—",
      propertyTitle: dispute.booking?.property?.name || "—",
      travelDate: dispute.booking?.travelDate,
      grossAmount: Number(dispute.booking?.grossAmount) || 0,
      currency: dispute.booking?.currency || "USD",
    })),
    pagination: payload.pagination || null,
  };
}

export async function createRefundRequest(payload) {
  if (staysUsesMockData) return staysMock.createRefundRequest(payload);
  const response = await api.post(`${BASE}/disputes`, payload, requestConfig);
  return response.data?.data;
}

export async function withdrawRefundRequest(id) {
  if (staysUsesMockData) return staysMock.withdrawRefundRequest(id);
  const response = await api.patch(`${BASE}/disputes/${id}/withdraw`, {}, requestConfig);
  return response.data?.data;
}

export async function fetchPayoutMethods() {
  if (staysUsesMockData) return staysMock.listPayoutMethods();
  const response = await api.get(`${BASE}/payout-methods/me`, requestConfig);
  const payload = response.data?.data || {};
  return payload.methods || [];
}

export async function createPayoutMethod(data) {
  if (staysUsesMockData) return staysMock.createPayoutMethod(data);
  const response = await api.post(`${BASE}/payout-methods`, data, requestConfig);
  return response.data?.data;
}

export async function updatePayoutMethod(id, data) {
  if (staysUsesMockData) return staysMock.updatePayoutMethod(id, data);
  const response = await api.patch(`${BASE}/payout-methods/${id}`, data, requestConfig);
  return response.data?.data;
}

export async function deletePayoutMethod(id) {
  if (staysUsesMockData) return staysMock.deletePayoutMethod(id);
  const response = await api.delete(`${BASE}/payout-methods/${id}`, requestConfig);
  return response.data?.data;
}

/* ── Refund claims (the Refund Requests tab) ─────────────────────────────── */

export function mapClaim(claim) {
  const booking = claim?.booking || {};
  return {
    id: claim.id,
    claimNumber: claim.claimNumber,
    reason: claim.reason,
    details: claim.details || "",
    type: claim.type,
    requestedAmount: Number(claim.requestedAmount) || 0,
    status: claim.status,
    createdAt: claim.createdAt,
    reviewNote: claim.reviewNote || null,
    releasedAmount: Number(claim.releasedAmount) || 0,
    booking: {
      bookingNumber: booking.bookingNumber || "",
      total: Number(booking.grossAmount) || 0,
      currency: booking.currency || "USD",
      customerName: booking.customer?.name || "Guest",
      customerEmail: booking.customer?.email || "",
      propertyTitle: booking.property?.name || "",
    },
  };
}

export async function fetchSupplierClaims(status) {
  if (staysUsesMockData) return staysMock.getSupplierClaims(status);
  const response = await api.get(`${BASE}/refund-claims/supplier`, {
    ...requestConfig,
    params: status && status !== "ALL" ? { status } : {},
  });
  return (response.data?.data?.claims || []).map(mapClaim);
}

export async function approveClaim(id) {
  if (staysUsesMockData) return staysMock.approveClaim(id);
  const response = await api.patch(`${BASE}/refund-claims/supplier/${id}/approve`, {}, requestConfig);
  return mapClaim(response.data?.data?.claim);
}

export async function declineClaim(id, note) {
  if (staysUsesMockData) return staysMock.declineClaim(id, note);
  const response = await api.patch(
    `${BASE}/refund-claims/supplier/${id}/decline`,
    { note },
    requestConfig,
  );
  return mapClaim(response.data?.data?.claim);
}

export { formatCurrency };
