export const DIETARY_OPTIONS = [
  'Diabetic', 'Egg-free', 'Gluten-free', 'Halal', 'Keto', 'Kosher',
  'Lactose-free', 'Low-carb', 'Nut-free', 'Pescatarian',
  'Seafood/fish-free', 'Vegan', 'Vegetarian',
]

export const ACTIVITY_CATEGORIES = {
  'Air Activities': ['Hot air balloon ride', 'Helicopter tour', 'Paragliding', 'Skydiving'],
  'Classes/Lessons/Workshops': ['Cooking class', 'Art class', 'Dance lesson', 'Craft workshop', 'Photography tour'],
  'Dining Experience': ['Food tasting tour', 'Wine tasting / winery tour', 'Beer / brewery tour', 'Coffee / tea tasting', 'Street food tour', 'Dinner cruise'],
  'Fun & Games': ['Pub crawl / bar tour', 'Ghost / vampire tour', 'Street art / graffiti tour', 'Concert / live show', 'Cultural performance'],
  'Land & Outdoor Activities': ['Walking tour', 'Hiking / trekking', 'Bike tour', 'Segway tour', 'Horseback riding', 'ATV / 4WD tour', 'Zip-lining / canopy tour', 'Canyoning / rappelling', 'Safari / wildlife viewing'],
  'Snow Activities': ['Skiing', 'Snowboarding', 'Snowmobile tour', 'Sled tour'],
  'Spas': ['Spa / thermal baths', 'Wellness retreat'],
  'Water Activities': ['Boat cruise', 'Sailing trip', 'Scuba diving', 'Snorkeling', 'Kayaking / canoeing', 'White water rafting', 'Surfing / paddleboarding', 'Dolphin / whale watching', 'Jet skiing', 'Fishing charter', 'Glass bottom boat tour', 'Sunset cruise', 'Dinner cruise'],
}

export const TOUR_TRANSPORT_CATEGORIES = {
  'Air Transport': ['Helicopter', 'Airplane', 'Balloon', 'Glider'],
  'Land Transport': ['Bus / coach', 'Car', 'Vintage car', 'Train', 'Tram', 'Bike', 'Segway', 'Trolley', 'Public transportation', 'Cable car'],
  'Water Transport': ['Boat', 'Ferry', 'Yacht', 'Kayak', 'Canoe', 'Sailboat'],
}

export const TRANSPORT_SERVICE_CATEGORIES = {
  'Air Transports': ['Helicopter transfer', 'Airplane transfer', 'Hot air balloon ride', 'Charter flight'],
  'Land Transports': ['Bus / coach', 'Private car', 'Van', 'Shuttle service', 'Train', 'Tram', 'Trolley', 'Tuk tuk', 'Bike rental', 'Scooter rental'],
  'Passes': ['Airport Lounge Pass', 'Airport Parking', 'Bus Pass', 'Luggage Storage', 'Public Transit', 'Rail Pass', 'City Card', 'Hop-on hop-off pass'],
  'Water Transports': ['Ferry', 'Water taxi', 'Private boat', 'Speedboat', 'Yacht charter', 'Canoe / kayak rental'],
}

export const GYG_ACTIVITIES = [
  'Walking tour', 'Hiking / trekking', 'Bike tour', 'Segway tour',
  'ATV / 4WD tour', 'Helicopter tour', 'Hot air balloon ride',
  'Horseback riding', 'Zip-lining / canopy tour', 'Paragliding',
  'Skydiving', 'Safari / wildlife viewing', 'Canyoning / rappelling',
  'Boat cruise', 'Sailing trip', 'Scuba diving', 'Snorkeling',
  'Kayaking / canoeing', 'White water rafting', 'Surfing / paddleboarding',
  'Dolphin / whale watching', 'Jet skiing', 'Fishing charter',
  'Glass bottom boat tour', 'Cooking class', 'Food tasting tour',
  'Wine tasting / winery tour', 'Beer / brewery tour',
  'Coffee / tea tasting', 'Distillery tour / spirits tasting',
  'Street food tour', 'Guided museum tour', 'Historical / heritage tour',
  'Skip-the-line entry', 'Photography tour', 'Street art / graffiti tour',
  'Ghost / vampire tour', 'Architecture tour', 'Art class',
  'Dance lesson', 'Craft workshop', 'Dinner cruise', 'Sunset cruise',
  'Pub crawl / bar tour', 'Concert / live show', 'Cultural performance',
  'Vintage car / Vespa tour', 'Tuk tuk / pedicab tour',
  'Multi-day excursion', 'Spa / thermal baths',
]

export const GYG_PICKUP_TRANSPORT = {
  '2 wheels': ['Bike', 'Segway', 'Electric bike', 'Mountain bike', 'Motorcycle', 'Scooter'],
  'Car / bus': ['Car', 'Limousine', 'Jeep / SUV', 'Van', 'Bus / coach', 'Electric car', 'Vintage car', 'Black cab'],
  Water: ['Gondola', 'Water taxi', 'Other water transport'],
  Other: ['Quad ATV', 'Pedicab / rickshaw', 'Trike', 'Tuk tuk/auto', 'Motorized tuk tuk/auto', 'Golf cart'],
  'On foot': ['On foot'],
}

export const GYG_TRANSPORT_TYPES = [
  'Bike', 'Segway', 'Electric bike', 'Mountain bike', 'Motorcycle', 'Scooter',
  'Car', 'Limousine', 'Jeep / SUV', 'Van', 'Bus / coach', 'Electric car',
  'Vintage car', 'Black cab', 'Sailboat', 'Ferry', 'Gondola', 'Duck boat',
  'Sightseeing cruise', 'Water taxi', 'Jetski', 'Riverboat', 'Kayak', 'Raft',
  'Catamaran', 'Speedboat', 'Yacht', 'Canoe', 'Paddleboard', 'Surfboard',
  'Submarine', 'Other water transport', 'Glass bottom boat', 'Lake cruise',
  'Banana boat', 'Beer boat', 'Airboat', 'Dhow', 'Train', 'Tram', 'Subway',
  'Helicopter', 'Airplane', 'Balloon', 'Glider', 'Public transportation',
  'Cable car', 'Quad ATV', 'Pedicab / rickshaw', 'Horse carriage', 'Camel',
  'Snowmobile', 'Sled', 'Other animal', 'Beer bike', 'Trike',
  'Tuk tuk/auto', 'Motorized tuk tuk/auto', 'Golf cart', 'On foot', 'Horse',
  'Trolley',
]

export const GYG_LANGUAGES = [
  'Abkhazian', 'Afar', 'Afrikaans', 'Albanian', 'Amharic', 'Arabic',
  'Armenian', 'Assamese', 'Aymara', 'Azerbaijani', 'Bashkir', 'Basque',
  'Bengali', 'Bhutani', 'Bihari', 'Bislama', 'Breton', 'Bulgarian',
  'Burmese', 'Byelorussian', 'Cambodian', 'Catalan', 'Chinese', 'Corsican',
  'Croatian', 'Czech', 'Danish', 'Dutch', 'English', 'Esperanto',
  'Estonian', 'Faeroese', 'Fiji', 'Finnish', 'French', 'Frisian',
  'Galician', 'Georgian', 'German', 'Greek', 'Greenlandic', 'Guarani',
  'Gujarati', 'Hausa', 'Hebrew', 'Hindi', 'Hungarian', 'Icelandic',
  'Indonesian', 'Interlingua', 'Interlingue', 'Inupiak',
  'Inuktitut (Eskimo)', 'Irish', 'Italian', 'Japanese', 'Javanese',
  'Kannada', 'Kashmiri', 'Kazakh', 'Kinyarwanda', 'Kirghiz', 'Kirundi',
  'Korean', 'Kurdish', 'Laothian', 'Latin', 'Latvian, Lettish', 'Lingala',
  'Lithuanian', 'Macedonian', 'Malagasy', 'Malay', 'Malayalam', 'Maltese',
  'Maori', 'Marathi', 'Moldavian', 'Mongolian', 'Nauru', 'Nepali',
  'Norwegian', 'Occitan', 'Oriya', 'Pashto, Pushto', 'Persian', 'Polish',
  'Portuguese', 'Punjabi', 'Quechua', 'Rhaeto-Romance', 'Romanian',
  'Russian', 'Samoan', 'Sangro', 'Sanskrit', 'Scots Gaelic', 'Serbian',
  'Serbo-Croatian', 'Sesotho', 'Setswana', 'Shona', 'Sindhi', 'Sinhala',
  'Siswati', 'Slovak', 'Slovenian', 'Somali', 'Spanish', 'Sudanese',
  'Swahili', 'Swedish', 'Tagalog', 'Tajik', 'Tamil', 'Tatar', 'Telugu',
  'Thai', 'Tibetan', 'Tigrinya', 'Tonga', 'Tsonga', 'Turkish', 'Turkmen',
  'Twi', 'Uigur', 'Ukrainian', 'Urdu', 'Uzbek', 'Vietnamese', 'Volapuk',
  'Welsh', 'Wolof', 'Xhosa', 'Yiddish (former ji)', 'Yoruba', 'Zhuang',
  'Zulu', 'Bosnian', 'Traditional Chinese',
]

export const GYG_MANDATORY_ITEMS = [
  'Beachwear', 'Binoculars', 'Biodegradable sunscreen',
  'Biodegradable insect repellent', 'Boating licence', 'Camera', 'Cash',
  'Change of clothes', 'Charged Smartphone', 'Child safety seat',
  'Climbing gear', 'Closed-toe shoes', 'Clothes that can get dirty',
  'Collared shirt', 'Comfortable clothes', 'Comfortable shoes',
  'Cooking equipment', 'Credit card', 'Cycling clothing', 'Daypack',
  'Deposit', 'Disability card', 'Dive log', 'Diving certification',
  'Downloaded app', 'Drinks', "Driver's license",
  'Face mask or protective covering', 'FFP2 mask', 'First aid kit',
  'Fishing license', 'Flashlight', 'Flip-flops', 'Food', 'Food and drinks',
  'Game box', 'Garbage bag', 'Gloves', 'Goggles', 'Trekking gear',
  'GPS/map', 'Hair tie', 'Hand sanitizer or tissues', 'Hat',
  'Head covering or kippah', 'Headphones', 'Headscarf', 'Helmet',
  'Hiking pants', 'Hiking shoes', 'Ingredients', 'Insect repellent',
  "International driver's license", 'Internet access', 'Jacket',
  'Breathable clothing', 'Long pants', 'Long-sleeved shirt', 'Medical mask',
  'Medical statement', 'Motion sickness prevention', 'Outdoor clothing',
  'Pacemaker card', 'Packed lunch', 'Passport', 'Passport, copy accepted',
  'Passport or ID card', 'Passport or ID card for children',
  'Passport or ID card, copy accepted', 'Passport-sized photo', 'Pen',
  'Personal medication', 'Pillow', 'Power bank', 'Public transport ticket',
  'Quick-dry clothing', 'Rain gear', 'Reusable water bottle', 'Sandals',
  'Sarong', 'Scarf', 'Shorts', 'Signed waiver', 'Sleeping bag', 'Snacks',
  'Snorkeling gear', 'Snow clothing', 'Socks', 'Sports shoes', 'Sportswear',
  'Storage device', 'Student card', 'Sunglasses', 'Sun hat', 'Sunscreen',
  'Swimming cap', 'Swimwear', 'Tent', 'Thermal clothing', 'Tie',
  'Toiletries', 'Towel', 'Travel insurance', 'Tripod', 'T-shirt',
  'Umbrella', 'ID card, copy accepted', 'Visa, if required',
  'Warm clothing', 'Warm shoes', 'Water', 'Waterproof bag',
  'Waterproof camera', 'Waterproof shoes', 'Water shoes',
  'Weather-appropriate clothing', 'Wetsuit', 'Windbreaker',
  'Winter sports gear', 'Your own vehicle',
]

export const GYG_NOT_ALLOWED = [
  'Alcohol and drugs', 'Audio recording', 'Baby carriages',
  'Baby strollers', 'Bachelor & bachelorette party groups', 'Party groups',
  'Backpacks', 'Bags', 'Bare feet', 'Bikes', 'Boots', 'Bright colors',
  'Cameras', 'Cellphones', 'Chewing gum', 'Climbing', 'Cooler', 'Crutches',
  'Diving', 'Handcarts', 'Alcoholic drinks in the vehicle',
  'Drinks in the vehicle', 'Drinks', 'Drones', 'Food in the vehicle',
  'Electric wheelchairs', 'Electronic devices', 'Explosive substances',
  'Feeding animals', 'Firework', 'Fishing', 'Flashlight',
  'Flash photography', 'Food', 'Food and drinks',
  'Food and drinks in the vehicle', 'Glass objects', 'Hats', 'Headphones',
  'High-heeled shoes', 'Shoes indoors', 'Insect repellent', 'Intoxication',
  'Jeans', 'Jewelry', 'Jumping', 'Littering', 'Luggage or large bags',
  'Making fire', 'Making noise', 'Military-style clothing',
  'Mobility scooters', 'Loose clothing', 'Non-folding strollers',
  'Non-folding wheelchairs', 'Waterproof cameras', 'Nudity',
  'Open-toed shoes', 'Oversize luggage', 'Padlocks', 'Pets',
  'Pets (assistance dogs allowed)', 'Photography inside', 'Plastic bags',
  'Plastic bottles', 'Professional cameras', 'Red wine',
  'Riding the animals', 'Ripped clothing', 'Sandals or flip flops',
  'Scooter', 'See-through clothing', 'Selfie sticks', 'Shoes', 'Shorts',
  'Short skirts', 'Skateboards', 'Skates', 'Skirts', 'Sleeveless shirts',
  'Slippers', 'Smoking', 'Smoking indoors', 'Smoking in the vehicle',
  'Snorkeling', 'Speakers', 'Sports shoes', 'Sportswear',
  'Sprays or Aerosols', 'Strong fragrances', 'Sunglasses', 'Sunscreen',
  'Surfboards', 'Swimming', 'Swimwear', 'Tablets/iPads',
  'Tight clothing', 'Touching the exhibits', 'Touching marine life',
  'Touching animals', 'Touching plants', 'Tripods', 'Umbrellas',
  'Unaccompanied minors', 'Visible tattoos', 'Valuables', 'Vaping',
  'Video recording', 'Walking frames', 'Walking sticks',
  'Weapons or sharp objects', 'Wearing a costume',
]

export const GYG_NOT_SUITABLE_FOR = [
  'People over 70 years', 'People over 95 years',
  'People with altitude sickness', 'Babies under 1 year',
  'Children under 10 years', 'Children under 11 years',
  'Children under 12 years', 'Children under 13 years',
  'Children under 14 years', 'Children under 15 years',
  'Children under 16 years', 'Children under 18 years',
  'Children under 2 years', 'Children under 3 years',
  'Children under 4 years', 'Children under 5 years',
  'Children under 6 years', 'Children under 7 years',
  'Children under 8 years', 'Children under 3 ft (90 cm)',
  'Children under 9 years', 'Cruise ship guests',
  'People with diabetes', 'Divers without certification',
  'People diving up to 24 hours prior', 'Drivers under 18 years',
  'Drivers under 21 years', 'Drivers under 16 years',
  'Hearing-impaired people', 'People with high blood pressure',
  'People with lactose intolerance', 'People with low level of fitness',
  'Non-swimmers', 'People with nut allergies',
  'People over 287 lbs (130 kg)', 'People over 309 lbs (140 kg)',
  'People over 209 lbs (95 kg)', 'People afraid of heights',
  'People over 220 lbs (100 kg)', 'People over 243 lbs (110 kg)',
  'People over 254 lbs (115 kg)', 'People over 260 lbs (118 kg)',
  'People over 275 lbs (125 kg)', 'People over 297 lbs (135 kg)',
  'People over 331 lbs (150 kg)', 'People over 5 ft 9 in (180 cm)',
  'People over 6 ft 6 in (200 cm)', 'People over 200 lbs (91 kg)',
  'People over 230 lbs (104 kg)', 'People over 250 lbs (113 kg)',
  'People over 264 lbs (120 kg)', 'People over 270 lbs (122 kg)',
  'People over 280 lbs (127 kg)', 'People over 300 lbs (136 kg)',
  'People over 350 lbs (159 kg)', 'People over 55 years',
  'People over 60 years', 'People over 65 years', 'People over 75 years',
  'People prone to seasickness', 'People under 3 ft 3 in (100 cm)',
  'People under 3 ft 6 in (110 cm)', 'People under 3 ft 9 in (120 cm)',
  'People under 4 ft 3 in (130 cm)', 'People under 4 ft 4 in (135 cm)',
  'People under 4 ft 6 in (140 cm)', 'People under 4 ft 8 in (145 cm)',
  'People under 4 ft 9 in (150 cm)', 'People under 5 ft 1 in (155 cm)',
  'People under 5 ft 2 in (160 cm)', 'People under 17 years',
  'People under 19 years', 'Children under 44 lbs (20 kg)',
  'People under 20 years', 'People under 21 years',
  'People under 66 lbs (30 kg)', 'People under 77 lbs (35 kg)',
  'People under 88 lbs (40 kg)', 'People under 99 lbs (45 kg)',
  'Children under 50 lbs (23 kg)',
  "People who can't drive manual transmission",
  "People who can't ride a bike", 'People with a cold',
  'People with animal allergies', 'People with back problems',
  'People with claustrophobia', 'People with epilepsy',
  'People with food allergies', 'People with gluten intolerance',
  'People with haemophilia', 'People with heart problems',
  'People with insect allergies', 'People with kidney problems',
  'People with mobility impairments', 'People with motion sickness',
  "People without driver's license", 'People without experience',
  'People with recent surgeries', 'People with respiratory issues',
  'People with vertigo', 'People with pre-existing medical conditions',
  'Pregnant women', 'People over 80 years',
  'Children under 33 lbs (15 kg)', 'Vegans', 'Vegetarians',
  'Visually impaired people', 'Wheelchair users',
]
