import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router-dom';

const {
  fetchFinanceSummaryMock,
  fetchFinanceEarningsMock,
  fetchPayoutRequestsMock,
  fetchPayoutMethodsMock,
  fetchFinanceDisputesMock,
  getFinanceChargesMock,
  updatePayoutSettingsMock,
  createPayoutRequestMock,
  fetchMyInvoicesMock,
  requestEarlyPayoutMock,
} = vi.hoisted(() => ({
  fetchFinanceSummaryMock: vi.fn(),
  fetchFinanceEarningsMock: vi.fn(),
  fetchPayoutRequestsMock: vi.fn(),
  fetchPayoutMethodsMock: vi.fn(),
  fetchFinanceDisputesMock: vi.fn(),
  getFinanceChargesMock: vi.fn(),
  updatePayoutSettingsMock: vi.fn(),
  createPayoutRequestMock: vi.fn(),
  fetchMyInvoicesMock: vi.fn(),
  requestEarlyPayoutMock: vi.fn(),
}));

vi.mock('../../api', () => ({
  fetchFinanceSummary: fetchFinanceSummaryMock,
  fetchFinanceEarnings: fetchFinanceEarningsMock,
  fetchPayoutRequests: fetchPayoutRequestsMock,
  fetchPayoutMethods: fetchPayoutMethodsMock,
  fetchFinanceDisputes: fetchFinanceDisputesMock,
  getFinanceCharges: getFinanceChargesMock,
  updatePayoutSettings: updatePayoutSettingsMock,
  createPayoutRequest: createPayoutRequestMock,
  fetchMyInvoices: fetchMyInvoicesMock,
  requestEarlyPayout: requestEarlyPayoutMock,
  cancelPayoutRequest: vi.fn(),
  createPayoutMethod: vi.fn(),
  deletePayoutMethod: vi.fn(),
  createRefundRequest: vi.fn(),
  withdrawRefundRequest: vi.fn(),
  fetchPayoutSettings: vi.fn(),
  fetchPayouts: vi.fn(),
  updatePayoutMethod: vi.fn(),
}));

vi.mock('@/stores/authStore', () => ({
  getAuthToken: () => 'test-token',
  useAuthStore: () => ({ user: { id: 'u1', name: 'Expedition-Go Tours' } }),
}));

// The claims tab renders its own page; keep it out of these assertions.
vi.mock('@/features/refund-claims/pages/RefundClaimsPage', () => ({ default: () => null }));
vi.mock('../../components/PayoutMethodFormSheet', () => ({ default: () => null }));

// Real layout, no animation: these tests are about what the page *says*, and
// framer-motion's enter/exit cycle would leave elements mid-transition.
// Motion-only props are stripped rather than destructured away, because
// `no-unused-vars` counts a destructured binding that is never read.
const MOTION_ONLY_PROPS = new Set([
  'initial', 'animate', 'exit', 'transition', 'layoutId', 'layout',
  'variants', 'custom', 'whileHover', 'whileTap', 'onAnimationStart',
]);

vi.mock('framer-motion', () => ({
  motion: new Proxy(
    {},
    {
      get: (_t, tag) => (props) => {
        const domProps = {};
        for (const [key, value] of Object.entries(props || {})) {
          if (!MOTION_ONLY_PROPS.has(key)) domProps[key] = value;
        }
        return typeof tag === 'string' ? React.createElement(tag, domProps) : null;
      },
    }
  ),
  AnimatePresence: ({ children }) => children,
}));

import React from 'react';
import FinancePage from '../FinancePage';

/**
 * The supplier this page was reported against, as it actually stood: 15 bookings
 * worth $1,849.96, of which 12 had already been swept into an auto-generated
 * request by the 05 Oct run, 2 were still waiting on their travel dates and 1
 * had been cancelled. ELIGIBLE was zero.
 *
 * Every assertion below is a claim the old page got wrong about exactly this
 * ledger, so the fixture is the regression test as much as the tests are.
 */
const REAL_LEDGER = {
  availableBalance: { amount: 0, currency: 'USD', bookingCount: 0 },
  pendingClearance: { amount: 433.5, currency: 'USD', bookingCount: 2, clearanceBufferDays: 0 },
  inReview: {
    total: 1263.46,
    byCurrency: { USD: 1263.46 },
    requestCount: 1,
    bookingCount: 12,
    latestRequest: {
      id: 'pr9',
      reference: 'PR-20261005-998363WCYJ',
      amount: 1263.46,
      currency: 'USD',
      status: 'PROCESSING',
      bookingCount: 12,
      autoGenerated: true,
      cycleLabel: 'Sep 28 – Oct 4',
      cycleStartDate: '2026-09-28T00:00:00.000Z',
      cycleEndDate: '2026-10-04T23:59:59.999Z',
      createdAt: '2026-10-05T00:26:00.000Z',
    },
  },
  paidOut: { total: 153, currency: 'USD' },
  payoutCounts: { PENDING: 2, ELIGIBLE: 0, REQUESTED: 12, PAID: 0, DISPUTED: 0, CANCELLED: 1 },
  // WEEKLY: the run for Mon 12 Oct. The manual window is the 24 hours leading
  // into it — Sun 11 Oct to Mon 12 Oct — and it is shut today, 5 Oct.
  nextEligibleAt: '2026-10-07T00:00:00.000Z',
  withdrawalWindow: {
    open: false,
    opensAt: '2026-10-11T00:00:00.000Z',
    closesAt: '2026-10-12T00:00:00.000Z',
    cycleLabel: 'Oct 5–11',
    runDay: '2026-10-12T00:00:00.000Z',
    source: 'schedule',
  },
  payoutPlan: {
    autoManaged: true,
    cycle: 'WEEKLY',
    scheduleLabel: 'Every week — paid every Monday',
    scheduleShortLabel: 'Weekly',
    runDays: 'Every Monday',
    nextRunAt: '2026-10-12T00:00:00.000Z',
    nextRunPeriodLabel: 'Oct 5–11',
    lastRunAt: '2026-10-05T00:00:00.000Z',
    effectiveAt: '2026-10-01T00:00:00.000Z',
    pendingCycle: null,
    pendingEffectiveAt: null,
    autoRunsEnabled: true,
    hasVerifiedPayoutMethod: true,
    options: [
      { value: 'WEEKLY', shortLabel: 'Weekly', runDays: 'Every Monday', label: 'Every week — paid every Monday', description: 'Weekly payouts.' },
      { value: 'TWICE_MONTHLY', shortLabel: 'Twice a month', runDays: 'The 1st & 15th', label: 'Twice a month — paid on the 1st & 15th', description: 'Twice-monthly payouts.' },
      { value: 'MONTHLY', shortLabel: 'Monthly', runDays: 'The 1st of each month', label: 'Monthly — paid on the 1st', description: 'Monthly payouts.' },
    ],
  },
};

const bookingRow = (over = {}) => ({
  id: 'b1',
  bookingNumber: 'GHA-1001',
  tourTitle: 'Kakum Canopy Walk',
  travelDate: '2026-10-06T00:00:00.000Z',
  supplierPayout: 216.75,
  grossAmount: 250,
  platformCommission: 33.25,
  currency: 'USD',
  payoutStatus: 'PENDING',
  paymentStatus: 'SUCCEEDED',
  bookingStatus: 'CONFIRMED',
  ...over,
});

const emptyPage = { earnings: [], pagination: { current: 1, totalPages: 1, totalCount: 0 } };

function renderPage(tab) {
  return render(
    <MemoryRouter initialEntries={[tab ? `/finance?tab=${tab}` : '/finance']}>
      <FinancePage />
    </MemoryRouter>
  );
}

const ready = () => waitFor(() => expect(fetchFinanceSummaryMock).toHaveBeenCalled());

beforeEach(() => {
  vi.clearAllMocks();
  fetchFinanceSummaryMock.mockResolvedValue(REAL_LEDGER);
  fetchFinanceEarningsMock.mockResolvedValue({
    earnings: [
      bookingRow({ id: 'r1', bookingNumber: 'GHA-1001', payoutStatus: 'REQUESTED', supplierPayout: 105.29 }),
      bookingRow({ id: 'r2', bookingNumber: 'GHA-1002', payoutStatus: 'REQUESTED', supplierPayout: 90 }),
      bookingRow({ id: 'p1', bookingNumber: 'GHA-1003', payoutStatus: 'PENDING', supplierPayout: 216.75 }),
      bookingRow({ id: 'x1', bookingNumber: 'GHA-1004', payoutStatus: 'CANCELLED', supplierPayout: 153 }),
    ],
    pagination: { current: 1, totalPages: 1, totalCount: 15 },
  });
  fetchPayoutRequestsMock.mockResolvedValue({ requests: [], pagination: null });
  fetchPayoutMethodsMock.mockResolvedValue([]);
  fetchFinanceDisputesMock.mockResolvedValue({ disputes: [], pagination: null });
  getFinanceChargesMock.mockResolvedValue({ charges: [], openTotals: [] });
  fetchMyInvoicesMock.mockResolvedValue({ invoices: [], pagination: null });
  requestEarlyPayoutMock.mockResolvedValue({ data: { invoices: [] } });
});

describe('FinancePage — the earnings list opens on All', () => {
  it('asks for every bucket rather than the narrowest one', async () => {
    renderPage();
    await ready();

    // The old default was ELIGIBLE. With that, this supplier — 15 bookings,
    // nothing eligible — opened onto an empty table.
    await waitFor(() => expect(fetchFinanceEarningsMock).toHaveBeenCalled());
    const params = fetchFinanceEarningsMock.mock.calls[0][0];
    expect(params.payoutStatus).toBeUndefined();
  });

  it('renders the bookings rather than denying they exist', async () => {
    renderPage();
    await ready();

    expect(await screen.findByText('GHA-1001')).toBeInTheDocument();
    expect(screen.queryByText(/no earnings yet/i)).not.toBeInTheDocument();
    expect(screen.queryByText(/earnings will appear once bookings/i)).not.toBeInTheDocument();
  });

  it('labels each bucket with its real count', async () => {
    renderPage();
    await ready();

    const requested = await screen.findByRole('button', { name: /in payout request/i });
    // 12 bookings are sitting in a payout request. Hiding that behind a filter
    // nobody had to open is how a supplier concluded they had earned nothing.
    expect(requested).toHaveTextContent('12');
  });
});

describe('FinancePage — empty states that are not false', () => {
  it('says No earnings only when the ledger really is empty', async () => {
    fetchFinanceSummaryMock.mockResolvedValue({
      ...REAL_LEDGER,
      payoutCounts: { PENDING: 0, ELIGIBLE: 0, REQUESTED: 0, PAID: 0, DISPUTED: 0, CANCELLED: 0 },
      availableBalance: { amount: 0, currency: 'USD', bookingCount: 0 },
      pendingClearance: { amount: 0, currency: 'USD', bookingCount: 0 },
      inReview: { total: 0, byCurrency: {}, requestCount: 0, bookingCount: 0, latestRequest: null },
      nextEligibleAt: null,
    });
    fetchFinanceEarningsMock.mockResolvedValue(emptyPage);

    renderPage();
    await ready();

    expect(await screen.findByText(/no earnings yet/i)).toBeInTheDocument();
  });

  it('names the empty filter instead, and links to where the bookings went', async () => {
    fetchFinanceEarningsMock.mockResolvedValue(emptyPage);

    renderPage();
    await ready();

    // 15 bookings exist. "No earnings yet" here is the bug that was reported.
    const empty = await screen.findByTestId('earnings-empty-state');
    expect(screen.queryByText(/no earnings yet/i)).not.toBeInTheDocument();
    expect(within(empty).getByText(/nothing all yet/i)).toBeInTheDocument();
    expect(within(empty).getByText(/15 bookings in total/i)).toBeInTheDocument();

    // And the buckets holding them are one click away, with counts.
    await userEvent.click(within(empty).getByRole('button', { name: /in payout request\s*12/i }));

    await waitFor(() => {
      const last = fetchFinanceEarningsMock.mock.calls.at(-1)[0];
      expect(last.payoutStatus).toBe('REQUESTED');
    });
  });

  it('does not offer a jump to an empty bucket', async () => {
    fetchFinanceEarningsMock.mockResolvedValue(emptyPage);

    renderPage();
    await ready();

    const empty = await screen.findByTestId('earnings-empty-state');
    // Nothing was ever paid, so a "Paid" escape hatch would be a dead link.
    expect(within(empty).queryByRole('button', { name: /^Paid/ })).not.toBeInTheDocument();
    // But the three buckets that do hold bookings are all offered.
    expect(within(empty).getAllByRole('button')).toHaveLength(3);
  });
});

describe('FinancePage — while a payout is in flight', () => {
  it('leads with the request instead of an empty request button', async () => {
    renderPage();
    await ready();

    const status = await screen.findByTestId('payout-in-flight-status');
    expect(within(status).getByText(/in review/i)).toBeInTheDocument();
    expect(within(status).getByText('PR-20261005-998363WCYJ')).toBeInTheDocument();
    expect(within(status).getByText(/12 bookings/)).toBeInTheDocument();
    // Says who asked for it: this one came from the scheduler, not the supplier.
    expect(within(status).getByText(/generated automatically/i)).toBeInTheDocument();

    // The $0.00 button is gone rather than merely disabled.
    expect(screen.queryByRole('button', { name: /request payout/i })).not.toBeInTheDocument();
  });

  it('never offers $0.00 as something to collect', async () => {
    renderPage();
    await ready();
    await screen.findByTestId('payout-in-flight-status');

    // The "Available for payout" stat reading $0.00 is honest — there genuinely
    // is nothing withdrawable. What is not honest is a control *offering* $0.00,
    // which is what the old card did on the one day of the cycle it appeared.
    const controls = [...document.querySelectorAll('button, a')];
    const offering = controls.filter((el) => /\$0\.00/.test(el.textContent || ''));
    expect(offering.map((el) => el.textContent.trim())).toEqual([]);

    // Nor a line of prose claiming money is accumulating when none is.
    expect(document.body.textContent).not.toMatch(/\$0\.00 accumulating/i);
  });

  it('still shows the pending balance and when it clears', async () => {
    renderPage();
    await ready();

    // $433.50 is real money that has not cleared yet, and the schedule card used
    // to describe the accumulating figure instead — "$0.00 accumulating" —
    // which is true of the eligible balance and useless about this one.
    // "Pending clearance" is both the stat card's label and a filter pill, so
    // anchor on the label element rather than the text.
    const label = await screen.findByText('Pending clearance', { selector: 'p' });
    const pendingCard = label.closest('div').parentElement;
    expect(within(pendingCard).getByText('$433.50')).toBeInTheDocument();
    expect(within(pendingCard).getByText(/next clears/i)).toBeInTheDocument();
  });

  it('explains a blocked request in visible text, not a tooltip', async () => {
    // Money in hand, but the window is shut, and no in-flight request — so the
    // button renders disabled and the reason is "come back on the 11th".
    fetchFinanceSummaryMock.mockResolvedValue({
      ...REAL_LEDGER,
      availableBalance: { amount: 750, currency: 'USD', bookingCount: 4 },
      inReview: { total: 0, byCurrency: {}, requestCount: 0, bookingCount: 0, latestRequest: null },
    });

    renderPage();
    await ready();

    const btn = await screen.findByRole('button', { name: /^request payout$/i });
    expect(btn).toBeDisabled();
    // A disabled element emits no pointer events, so a `title` tooltip can never
    // appear — the reason has to be text on the page.
    expect(btn).not.toHaveAttribute('title');
    expect(screen.getByText(/you can request early from/i)).toBeVisible();
  });
});

describe('FinancePage — the banner', () => {
  it('never renders a zero-length window', async () => {
    renderPage();
    await ready();

    const banner = await screen.findByText(/payouts are generated automatically/i);
    const text = banner.closest('p')?.textContent || '';

    // "between 05 Oct 2026 and 05 Oct 2026" — two identical dates from a 24-hour
    // window, which reads as a window that is somehow always open and never open.
    expect(text).not.toMatch(/between\s+\S+\s+and\s+\S+/i);
    expect(text).toMatch(/next run is/i);
  });

  it('offers the early-request route only when it can actually be used', async () => {
    renderPage();
    await ready();

    const banner = await screen.findByText(/payouts are generated automatically/i);
    // Nothing is eligible and a request is already in flight, so advertising a
    // way to request one is an invitation to a dead end.
    expect(banner.closest('p')?.textContent || '').not.toMatch(/request one early/i);
  });

  it('mentions the early-request route, by its opening date, when there is money', async () => {
    fetchFinanceSummaryMock.mockResolvedValue({
      ...REAL_LEDGER,
      availableBalance: { amount: 750, currency: 'USD', bookingCount: 4 },
      inReview: { total: 0, byCurrency: {}, requestCount: 0, bookingCount: 0, latestRequest: null },
    });

    renderPage();
    await ready();

    expect(await screen.findByText(/request one early from/i)).toBeInTheDocument();
  });
});

describe('FinancePage — the schedule is manageable here', () => {
  it('opens the cadence chooser from the card', async () => {
    renderPage();
    await ready();

    expect(screen.queryByRole('radio', { name: /^Weekly\b/i })).not.toBeInTheDocument();

    await userEvent.click(await screen.findByRole('button', { name: /manage schedule/i }));

    // The cadence chooser used to live only under Settings, so a supplier told
    // "paid automatically on your weekly schedule" had no way to act on it.
    expect(await screen.findByRole('radio', { name: /^Weekly\b/i })).toBeInTheDocument();
    expect(screen.getByRole('radio', { name: /^Twice a month\b/i })).toBeInTheDocument();
  });

  it('refetches the summary after a schedule change', async () => {
    updatePayoutSettingsMock.mockResolvedValue({
      ...REAL_LEDGER.payoutPlan,
      pendingCycle: 'MONTHLY',
      pendingEffectiveAt: '2026-11-01T00:00:00.000Z',
    });

    renderPage();
    await ready();
    await userEvent.click(await screen.findByRole('button', { name: /manage schedule/i }));
    await userEvent.click(await screen.findByRole('radio', { name: /^Monthly\b/i }));
    await userEvent.click(screen.getByRole('button', { name: /save schedule/i }));

    await waitFor(() => expect(updatePayoutSettingsMock).toHaveBeenCalledWith('MONTHLY'));
    // The card is rendered from the summary, so without a refetch it would keep
    // describing the schedule the supplier just changed.
    await waitFor(() => {
      const calls = fetchFinanceSummaryMock.mock.calls.length;
      expect(calls).toBeGreaterThan(1);
    });
  });
});

describe('FinancePage — the legacy non-enrolled path still works', () => {
  // The opt-out path keeps its own withdrawal window. It must not regress into
  // the auto-schedule copy just because the default changed.
  const legacySummary = {
    ...REAL_LEDGER,
    payoutPlan: { ...REAL_LEDGER.payoutPlan, autoManaged: false, cycle: null },
    withdrawalWindow: {
      open: true,
      opensAt: '2026-10-01T00:00:00.000Z',
      closesAt: '2026-10-15T23:59:59.999Z',
      cycleLabel: 'Oct 1–15',
      source: 'legacy',
    },
  };

  it('shows the calendar cycle and no schedule card', async () => {
    fetchFinanceSummaryMock.mockResolvedValue(legacySummary);

    renderPage();
    await ready();

    expect(await screen.findByText(/current payout cycle/i)).toBeInTheDocument();
    // The auto-schedule card is the thing that must not appear: it is the piece
    // that names a run date, a period and a "Manage schedule" control.
    expect(screen.queryByText(/^Next payout/)).not.toBeInTheDocument();
    expect(screen.queryByText(/^Covering/)).not.toBeInTheDocument();
    expect(screen.queryByRole('button', { name: /manage schedule/i })).not.toBeInTheDocument();
  });

  it('still refuses to name an amount it cannot pay out', async () => {
    fetchFinanceSummaryMock.mockResolvedValue(legacySummary);

    renderPage();
    await ready();

    const btn = await screen.findByRole('button', { name: /^request payout$/i });
    expect(btn).toBeDisabled();
    expect(btn).not.toHaveTextContent('$0.00');
  });

  it('still offers the request when the calendar window is open and there is money', async () => {
    fetchFinanceSummaryMock.mockResolvedValue({
      ...legacySummary,
      availableBalance: { amount: 900, currency: 'USD', bookingCount: 6 },
      inReview: { total: 0, byCurrency: {}, requestCount: 0, bookingCount: 0, latestRequest: null },
    });

    renderPage();
    await ready();

    const btn = await screen.findByRole('button', { name: /request payout/i });
    expect(btn).toBeEnabled();
    expect(btn).toHaveTextContent('$900.00');
  });
});

describe('FinancePage — the payout dialog', () => {
  // It shipped as a bare `fixed inset-0` overlay with no key handling, no role
  // and an unnamed icon-only close button. Measured in a real browser: Escape
  // left the overlay up indefinitely and Tab walked out into the sidebar.
  const openable = () => {
    fetchFinanceSummaryMock.mockResolvedValue({
      ...REAL_LEDGER,
      availableBalance: { amount: 811.91, currency: 'USD', bookingCount: 6 },
      inReview: { total: 0, byCurrency: {}, requestCount: 0, bookingCount: 0, latestRequest: null },
      withdrawalWindow: { ...REAL_LEDGER.withdrawalWindow, open: true },
    });
  };

  const openDialog = async () => {
    renderPage();
    await ready();
    await userEvent.click(await screen.findByRole('button', { name: /request payout/i }));
    return screen.findByRole('dialog');
  };

  it('announces itself as a modal dialog with a name', async () => {
    openable();
    const dialog = await openDialog();
    expect(dialog).toHaveAttribute('aria-modal', 'true');
    expect(dialog).toHaveAccessibleName('Request payout');
  });

  it('gives its close button an accessible name', async () => {
    openable();
    await openDialog();
    // It was an <X> icon and nothing else, so it was unlabelled to a screen reader.
    expect(screen.getByRole('button', { name: /close/i })).toBeInTheDocument();
  });

  it('closes on Escape', async () => {
    openable();
    await openDialog();
    await userEvent.keyboard('{Escape}');
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument());
  });

  it('returns focus to the button that opened it', async () => {
    openable();
    const trigger = await (async () => {
      renderPage();
      await ready();
      const b = await screen.findByRole('button', { name: /request payout/i });
      await userEvent.click(b);
      await screen.findByRole('dialog');
      return b;
    })();

    await userEvent.keyboard('{Escape}');
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument());
    expect(trigger).toHaveFocus();
  });

  it('puts focus on the close control, not on Submit', async () => {
    openable();
    await openDialog();
    await waitFor(() => expect(screen.getByRole('button', { name: /close/i })).toHaveFocus());
    expect(screen.getByRole('button', { name: /submit request/i })).not.toHaveFocus();
  });

  it('gives the refund dialog the same semantics', async () => {
    // It was the same bare overlay with the same missing role and key handling,
    // so it needed the same treatment rather than being left behind.
    // The refund modal is reached from the Refunds tab, not the Earnings one.
    renderPage('refunds');
    await ready();

    await userEvent.click(await screen.findByRole('button', { name: /request refund/i }));
    const dialog = await screen.findByRole('dialog');

    expect(dialog).toHaveAttribute('aria-modal', 'true');
    expect(dialog).toHaveAccessibleName('Request a refund');

    await userEvent.keyboard('{Escape}');
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument());
  });
});

/**
 * Finance v3: enrolled suppliers are paid via automatic invoices. The summary
 * then carries `balance` (unpaid invoices), `nextPayout` (the pending-window
 * projection with its exact invoiced/paid dates) and an invoice-sourced
 * withdrawal window — and the manual "Request payout" button becomes the
 * early-invoice accelerator (POST /finance/invoices).
 */
const ENROLLED_LEDGER = {
  ...REAL_LEDGER,
  inReview: { total: 0, byCurrency: {}, requestCount: 0, bookingCount: 0, latestRequest: null },
  payoutCounts: { PENDING: 2, ELIGIBLE: 0, REQUESTED: 0, PAID: 0, DISPUTED: 0, CANCELLED: 1 },
  balance: {
    byCurrency: [{ currency: 'USD', amount: 640.25 }],
    bookingCount: 3,
    openInvoiceCount: 2,
  },
  nextPayout: {
    window: {
      cycle: 'TWICE_MONTHLY',
      slot: 'A',
      label: 'Oct 1–15',
      start: '2026-10-01T00:00:00.000Z',
      end: '2026-10-15T23:59:59.999Z',
      invoicedOn: '2026-10-16T00:00:00.000Z',
      paidOn: '2026-10-20T00:00:00.000Z',
    },
    bookingCount: 4,
    grossTotal: 780,
    commissionTotal: 132.6,
    netTotal: 647.4,
    byCurrency: [{ currency: 'USD', grossTotal: 780, platformCommission: 132.6, supplierPayout: 647.4 }],
  },
  withdrawalWindow: {
    open: true,
    source: 'invoice',
    cycleLabel: 'Oct 1–15',
    opensAt: null,
    closesAt: null,
  },
  payoutPlan: {
    ...REAL_LEDGER.payoutPlan,
    cycle: 'TWICE_MONTHLY',
    scheduleLabel: 'Twice a month — invoiced on the 16th & 1st',
    scheduleShortLabel: 'Twice a month',
    runDays: 'The 16th & 1st',
    nextRunAt: '2026-10-16T00:00:00.000Z',
    nextRunPeriodLabel: 'Oct 1–15',
  },
};

const invoiceRow = {
  id: 'inv1',
  invoiceNumber: 'INV-2026-10-0001',
  status: 'INVOICED',
  cycle: 'TWICE_MONTHLY',
  cycleLabel: 'Oct 1–15',
  cycleStartDate: '2026-10-01T00:00:00.000Z',
  cycleEndDate: '2026-10-15T23:59:59.999Z',
  invoicedAt: '2026-10-16T00:00:00.000Z',
  paymentScheduledAt: '2026-10-20T00:00:00.000Z',
  paidAt: null,
  reference: '',
  grossTotal: 780,
  commissionTotal: 132.6,
  netTotal: 647.4,
  currency: 'USD',
  bookingCount: 4,
};

describe('FinancePage — finance v3: automatic invoices', () => {
  beforeEach(() => {
    fetchFinanceSummaryMock.mockResolvedValue(ENROLLED_LEDGER);
  });

  it('leads with Your balance (unpaid invoices) and Next payout with its dates', async () => {
    renderPage();
    await ready();

    expect(await screen.findByText('Your balance')).toBeInTheDocument();
    expect(screen.getByText('$640.25')).toBeInTheDocument();
    expect(screen.getByText('2 unpaid invoices')).toBeInTheDocument();

    expect(screen.getByText('Next payout')).toBeInTheDocument();
    expect(screen.getAllByText('$647.40').length).toBeGreaterThan(0);
    // Exact activity range and processing dates, beside the estimate.
    expect(screen.getAllByText(/Bookings .+–/).length).toBeGreaterThan(0);
    expect(screen.getAllByText(/Invoiced .*· paid/).length).toBeGreaterThan(0);
    expect(screen.queryByText('Available for payout')).not.toBeInTheDocument();
  });

  it('routes the request button through the early-invoice endpoint, not a v2 request', async () => {
    renderPage();
    await ready();

    const btn = await screen.findByRole('button', { name: /request early payout/i });
    expect(btn).toBeEnabled();
    expect(btn).toHaveTextContent('$647.40');

    await userEvent.click(btn);
    const dialog = await screen.findByRole('dialog');
    expect(dialog).toHaveAccessibleName('Request early payout');
    expect(within(dialog).getByText('Invoiced on')).toBeInTheDocument();
    expect(within(dialog).getByText('Paid on')).toBeInTheDocument();

    await userEvent.click(within(dialog).getByRole('button', { name: /create invoice/i }));
    await waitFor(() => expect(requestEarlyPayoutMock).toHaveBeenCalledTimes(1));
    expect(createPayoutRequestMock).not.toHaveBeenCalled();
  });

  it('lists invoices on the payouts tab instead of the empty legacy request state', async () => {
    fetchMyInvoicesMock.mockResolvedValue({
      invoices: [invoiceRow],
      pagination: { current: 1, totalPages: 1, totalCount: 1 },
    });
    renderPage('payouts');
    await ready();

    expect(await screen.findByText('INV-2026-10-0001')).toBeInTheDocument();
    expect(screen.getByText('Due')).toBeInTheDocument();
    expect(screen.queryByText('No payout requests yet')).not.toBeInTheDocument();
    // No legacy history to show, so no legacy header either.
    expect(screen.queryByText('Legacy payout requests')).not.toBeInTheDocument();
  });

  it('says the window is empty instead of offering a $0.00 request', async () => {
    fetchFinanceSummaryMock.mockResolvedValue({
      ...ENROLLED_LEDGER,
      nextPayout: { window: null, bookingCount: 0, grossTotal: 0, commissionTotal: 0, netTotal: 0, byCurrency: [] },
    });
    renderPage();
    await ready();

    const btn = await screen.findByRole('button', { name: /request early payout/i });
    expect(btn).toBeDisabled();
    expect(screen.getByText('Nothing is waiting on the current payout window yet.')).toBeInTheDocument();
  });
});
