export const FIELD_LABELS = {
  language: 'Language',
  category: 'Product type',
  activityType: 'Activity type',
  activitiesIncluded: 'Activities included',
  transportModes: 'Transport modes',
  transportServices: 'Transport services',
  cutoffMinutes: 'Cut-off time',
  lastMinuteBookings: 'Last-minute bookings',
  perSlotCutoff: 'Per-slot cut-off',
  perSlotCutoffs: 'Per-slot cut-off times',
  difficulty: 'Difficulty level',
  duration: 'Duration',
  durationUnit: 'Duration unit',
  accommodationIncluded: 'Accommodation included',
  title: 'Title',
  referenceCode: 'Reference code',
  shortDescription: 'Short description',
  fullDescription: 'Full description',
  highlights: 'Highlights',
  locations: 'Location',
  keywords: 'Keywords',
  whatsIncluded: "What's included",
  whatsNotIncluded: "What's not included",
  foodProvided: 'Food provided',
  meals: 'Meals',
  drinksIncluded: 'Drinks included',
  showDietaryRestrictions: 'Dietary restrictions',
  dietaryOptions: 'Dietary options',
  transportationProvided: 'Transportation provided',
  transportationType: 'Transportation type',
  guideType: 'Guide type',
  guideMaterials: 'Guide materials',
  photos: 'Photos',
  copyrightConfirmed: 'Copyright confirmation',
  notSuitableFor: 'Not suitable for',
  notAllowed: 'Not allowed',
  petFriendly: 'Pet friendly',
  mandatoryItems: 'Mandatory items',
  knowBeforeYouGo: 'Know before you go',
  emergencyPhone: 'Emergency phone number',
  voucherInfo: 'Voucher info',
  options: 'Options',
  meetingMode: 'Meeting mode',
  meetingPoint: 'Meeting point',
  meetingPoints: 'Meeting points',
  meetingPointPicture: 'Meeting point picture',
  meetingPointDescription: 'Meeting point description',
  arrivalTimeType: 'Arrival time type',
  arrivalTimeCustom: 'Arrival time',
  pickupType: 'Pickup type',
  pickupDescription: 'Pickup description',
  pickupTiming: 'Pickup timing',
  pickupFinalLocationTiming: 'Pickup final location timing',
  referenceStartTime: 'Reference start time',
  pickupAreas: 'Pickup areas',
  pickupLocations: 'Pickup locations',
  pickupGeoshape: 'Pickup geoshape',
  dropoffOption: 'Dropoff option',
  dropoffLocation: 'Dropoff location',
  dropoffDescription: 'Dropoff description',
  pricingModel: 'Pricing model',
  currency: 'Currency',
  scheduleType: 'Schedule type',
  scheduleName: 'Schedule name',
  scheduleStartDate: 'Start date',
  scheduleHasEndDate: 'End date',
  scheduleEndDate: 'End date',
  timeSlots: 'Time slots',
  operatingHoursStart: 'Operating hours start',
  operatingHoursEnd: 'Operating hours end',
  dateExceptions: 'Date exceptions',
  pricingApproach: 'Pricing approach',
  uniformPrice: 'Uniform price',
  pricingCategories: 'Pricing categories',
  'pricingCategories.tiers': 'Pricing categories — Tier prices',
  'pricingCategories.tiers.pricePerPerson': 'Pricing categories — Tier price',
  'pricingCategories.tiers.from': 'Pricing categories — Tier range',
  'pricingCategories.tiers.to': 'Pricing categories — Tier range',
  'pricingCategories.maxAge': 'Pricing categories — Max age',
  'pricingCategories.minAge': 'Pricing categories — Min age',
  'pricingCategories.name': 'Pricing categories — Name',
  'pricingCategories.price': 'Pricing categories — Price',
  weeklySchedule: 'Opening hours',
  minParticipants: 'Min participants',
  maxParticipants: 'Max participants',
  pricingTiers: 'Pricing tiers',
  groupSizes: 'Group sizes',
  additionalPersonsEnabled: 'Additional persons',
  additionalPersonPrice: 'Additional person price',
  maxGroupsPerTimeSlot: 'Max groups per time slot',
  cancellationType: 'Cancellation policy',
  supplierCanCancelBadWeather: 'Cancel for bad weather',
  supplierCanCancelNotEnoughTravelers: 'Cancel for not enough travelers',
}

const FIELD_STEP_MAP = {
  language: 1,
  category: 3,
  activityType: 3,
  transportModes: 3,
  transportServices: 3,
  cutoffMinutes: 16,
  lastMinuteBookings: 16,
  perSlotCutoff: 16,
  perSlotCutoffs: 16,
  difficulty: 3,
  duration: 3,
  durationUnit: 3,
  accommodationIncluded: 3,
  title: 2,
  referenceCode: 2,
  shortDescription: 4,
  fullDescription: 4,
  highlights: 4,
  locations: 5,
  keywords: 6,
  whatsIncluded: 7,
  whatsNotIncluded: 7,
  activitiesIncluded: 3,
  foodProvided: 7,
  meals: 7,
  drinksIncluded: 7,
  showDietaryRestrictions: 7,
  dietaryOptions: 7,
  guideType: 8,
  guideMaterials: 8,
  photos: 11,
  copyrightConfirmed: 11,
  notSuitableFor: 9,
  notAllowed: 9,
  petFriendly: 9,
  wheelchairAccessible: 9,
  mandatoryItems: 9,
  knowBeforeYouGo: 9,
  emergencyPhone: 9,
  voucherInfo: 9,
  options: 12,
  meetingMode: 13,
  meetingPoint: 13,
  meetingPoints: 13,
  meetingPointPicture: 13,
  meetingPointDescription: 13,
  arrivalTimeType: 13,
  arrivalTimeCustom: 13,
  pickupType: 13,
  pickupDescription: 13,
  pickupTiming: 13,
  pickupFinalLocationTiming: 13,
  referenceStartTime: 13,
  pickupAreas: 13,
  pickupLocations: 13,
  pickupGeoshape: 13,
  dropoffOption: 13,
  dropoffLocation: 13,
  dropoffDescription: 13,
  pricingModel: 15,
  currency: 15,
  scheduleType: 15,
  scheduleName: 15,
  scheduleStartDate: 15,
  scheduleEndDate: 15,
  timeSlots: 15,
  pricingApproach: 15,
  uniformPrice: 15,
  pricingCategories: 15,
  minParticipants: 15,
  maxParticipants: 15,
  pricingTiers: 15,
  groupSizes: 15,
  additionalPersonsEnabled: 15,
  additionalPersonPrice: 15,
  maxGroupsPerTimeSlot: 15,
  cancellationType: 10,
  supplierCanCancelBadWeather: 10,
  supplierCanCancelNotEnoughTravelers: 10,
}

export function getStepForField(fieldKey) {
  const baseKey = fieldKey.split('.')[0]
  return FIELD_STEP_MAP[baseKey] || null
}

export function getFieldLabel(fieldKey) {
  const exactLabel = FIELD_LABELS[fieldKey]
  if (exactLabel) return exactLabel

  const parts = fieldKey.split('.').filter(p => !/^\d+$/.test(p))

  if (parts.length >= 2) {
    const joinedKey = parts.join('.')
    const joinedLabel = FIELD_LABELS[joinedKey]
    if (joinedLabel) return joinedLabel
    const baseLabel = FIELD_LABELS[parts[0]] || parts[0]
    const fieldLabel = FIELD_LABELS[parts[1]] || parts[1]
    return `${baseLabel} — ${fieldLabel}`
  }

  return FIELD_LABELS[parts[0]] || parts[0] || fieldKey
}

export function scrollToField(fieldKey) {
  const el =
    document.querySelector(`[data-field="${CSS.escape(fieldKey)}"]`) ||
    document.getElementById(`field-${CSS.escape(fieldKey)}`)
  if (el) {
    el.scrollIntoView({ behavior: 'smooth', block: 'center' })
    const originalOutline = el.style.outline
    el.style.outline = '2px solid #ef4444'
    el.style.outlineOffset = '2px'
    setTimeout(() => { el.style.outline = originalOutline }, 3000)
    if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement || el instanceof HTMLSelectElement) {
      el.focus({ preventScroll: true })
    }
  }
}

const SECTION_LABELS = {
  language: 'Language',
  category: 'Category',
  activityType: 'Activity type',
  transportModes: 'Transport modes',
  transportServices: 'Transport services',
  cutoffMinutes: 'Cut-off',
  lastMinuteBookings: 'Last-minute bookings',
  perSlotCutoff: 'Per-slot cut-off',
  perSlotCutoffs: 'Per-slot cut-off',
  difficulty: 'Difficulty',
  duration: 'Duration',
  title: 'Title',
  shortDescription: 'Descriptions & highlights',
  fullDescription: 'Descriptions & highlights',
  highlights: 'Descriptions & highlights',
  locations: 'Location',
  keywords: 'Keywords',
  whatsIncluded: 'Inclusions',
  whatsNotIncluded: 'Inclusions',
  activitiesIncluded: 'Keywords',
  foodProvided: 'Inclusions',
  meals: 'Inclusions',
  drinksIncluded: 'Inclusions',
  dietaryOptions: 'Inclusions',
  transportationProvided: 'Inclusions',
  transportationType: 'Inclusions',
  guideType: 'Guide information',
  guideMaterials: 'Guide information',
  photos: 'Photos',
  copyrightConfirmed: 'Photos',
  notSuitableFor: 'Extra information',
  notAllowed: 'Extra information',
  petFriendly: 'Extra information',
  mandatoryItems: 'Extra information',
  knowBeforeYouGo: 'Extra information',
  emergencyPhone: 'Extra information',
  voucherInfo: 'Extra information',
  options: 'Options',
  meetingMode: 'Meeting point or pickup',
  meetingPoint: 'Meeting point or pickup',
  meetingPoints: 'Meeting point or pickup',
  meetingPointPicture: 'Meeting point or pickup',
  meetingPointDescription: 'Meeting point or pickup',
  arrivalTimeType: 'Meeting point or pickup',
  pickupType: 'Meeting point or pickup',
  pickupDescription: 'Meeting point or pickup',
  pickupTiming: 'Meeting point or pickup',
  pickupAreas: 'Meeting point or pickup',
  pickupLocations: 'Meeting point or pickup',
  dropoffOption: 'Meeting point or pickup',
  dropoffLocation: 'Meeting point or pickup',
  pricingModel: 'Availability & Pricing',
  currency: 'Availability & Pricing',
  scheduleType: 'Availability & Pricing',
  scheduleName: 'Availability & Pricing',
  scheduleStartDate: 'Availability & Pricing',
  scheduleEndDate: 'Availability & Pricing',
  timeSlots: 'Availability & Pricing',
  pricingApproach: 'Availability & Pricing',
  uniformPrice: 'Availability & Pricing',
  pricingCategories: 'Availability & Pricing',
  minParticipants: 'Availability & Pricing',
  maxParticipants: 'Availability & Pricing',
  pricingTiers: 'Availability & Pricing',
}

export function getSectionLabel(fieldKey) {
  const baseKey = fieldKey.split('.')[0]
  return SECTION_LABELS[baseKey] || FIELD_LABELS[baseKey] || baseKey
}
